# Description: "CloudDeploy Infrastructure"
Parameters:
  CodeDeployApp:
    Description: "CodeDeploy Application"
    Type: String
    Default : "csye6225-webapp"

  CodeDeployS3Bucket:
    Description: "CodeDeploy S3 Bucket"
    Type: String
    Default : "code-deploy-s3-bucket-csye-6225-demo"

  CodeDeployUser:
    Description: "UserName"
    Type: String
    Default : "ghactions"

Resources:
  # GH-Upload-To-S3 Policy for GitHub Actions to Upload to AWS S3
  GHUploadToS3Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com            
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Ref GHUploadToS3Policy

  GHUploadToS3Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: GHUploadToS3Policy
      Path: /
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
            Resource:
              - !Join [ "", [ "arn:aws:s3:::", !Ref CodeDeployS3Bucket, "/*" ] ]
        
          - Effect: Allow
            Action:
              - s3:Get*
              - s3:List*
            Resource:
              - !Join [ "", [ "arn:aws:s3:::", !Ref CodeDeployS3Bucket ] ]
      Users:
        - !Ref CodeDeployUser
  
  #GH-Code-Deploy Role for GitHub Actions to Call CodeDeploy
  GHCodeDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codedeploy.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Ref GHCodeDeployPolicy
      
  
  GHCodeDeployPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: GHCodeDeployPolicy
      Path: /
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - codedeploy:CreateDeployment
              - codedeploy:GetDeployment
              - codedeploy:GetDeploymentConfig
              - codedeploy:RegisterApplicationRevision
              - codedeploy:GetApplicationRevision
            Resource:
              - !Join [ "", [ "arn:aws:codedeploy:", !Ref AWS::Region, ":", !Ref AWS::AccountId, ":application:", !Ref CodeDeployApp ] ]
              - !Sub arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentconfig:CodeDeployDefault.OneAtATime
              - !Sub arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentconfig:CodeDeployDefault.HalfAtATime
              - !Sub arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentconfig:CodeDeployDefault.AllAtOnce
              - !Join [ "", [ "arn:aws:codedeploy:", !Ref AWS::Region, ":", !Ref AWS::AccountId, ":deploymentgroup:", !Ref CodeDeployApp, "/*" ] ]
            
      Users:
        - !Ref CodeDeployUser
         
  